name: workflow3
on:
  push:
    branches: 
      -'release-*' 
 
jobs:
  build:
      name: Build Java application
      runs-on: ubuntu-latest
      steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: build native with maven
        run: mvn -B package 
      - name: Upload jar for next job
        uses: actions/upload-artifact@v2
        with:
          name: target
          path: target
          retention-days: 1
          
  publish_in_dockerhub:
      name: Publish in DockerHub
      runs-on: ubuntu-latest
      needs: [build]
      env:
        IMAGE_NAME: items
      steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download Jar from previous job
        uses: actions/download-artifact@v2
        with:
          name: target
          path: target
      - name: Generate tag
        run: echo ::set-output name=tag::$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}"
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/items:${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/items:${{ steps.project.outputs.tag }}
