name: workflow4
on:
  schedule:
    - cron: '00 00 * * *'     
jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build native with Maven
      run: mvn -B package
    - name: Upload jar for next job
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: target/*.jar
        retention-days: 1
        
  publish_in_dockerhub:
    name: Publish in DockerHub
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Download jar from previous job
        uses: actions/download-artifact@v1
        with:
          name: target
          path: target/*.jar
      - name: Generate tag
        run: echo ::set-output name=tag::$(date +'%Y%m%d')
        id: project
      - name: Login to DockerHub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_TOKEN }}" 
      - name: Build image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/dev-${{ steps.project.outputs.tag }} .
      - name: Push image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/dev-${{ steps.project.outputs.tag }}
